name: Lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'LICENSE.txt'
      - 'doc/**/*.txt'
      - '**/AUTHORS'
      - '**/SPONSORS'
      - '**/TIPS'

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Run ruff check
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0

      - name: Run ruff format
        uses: astral-sh/ruff-action@0ce1b0bf8b818ef400413f810f8a11cdbda0034b # v4.0.0
        with:
          args: 'format --check'
