name: Lint

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
      - 'LICENSE.txt'
      - 'doc/**/*.txt'
      - '**/AUTHORS'
      - '**/SPONSORS'
      - '**/TIPS'

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run ruff check
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0

      - name: Run ruff format
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89 # v4.1.0
        with:
          args: 'format --check'
